# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildConfiguration
  value: 'Release'
- name: buildOutputFolder
  value: $(Build.ArtifactStagingDirectory)
trigger:
  branches:
    include:
    - refs/heads/master
pool:
  name: 'Neotechagentpool'  # The pool name for your self-hosted agent, replace with the actual pool name
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Neotechagentpool
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      ConnectedServiceName: a052c6a2-b1e2-446d-a8e4-9886931a5000
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: CmdLine@2
    inputs:
          script: |
            echo Artifact staging directory-Hello world-1
            echo  $(Build.ArtifactStagingDirectory)
            echo Hello world-1
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      ConnectedServiceName: a052c6a2-b1e2-446d-a8e4-9886931a5000
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      ConnectedServiceName: a052c6a2-b1e2-446d-a8e4-9886931a5000
      command: publish
      publishWebProjects: True
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      #TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
      #ArtifactName: 'drop'
      #publishLocation: 'Container'      
- job: Deploy
  displayName: 'Deploy to IIS Web Server'
  dependsOn: Job_1
  condition: succeeded()
  pool:
    name: 'Neotechagentpool'  # Ensure this is the correct pool with your self-hosted agent
  steps:
    # Step 1: Download build artifacts
    - task: DownloadBuildArtifacts@0
      displayName: 'Download build artifacts'
      inputs:
        buildType: 'specific'
        project: $(System.TeamProject)
        definition: '33'  # $(Build.DefinitionId)
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        #artifactName: 'drop'
        downloadPath: '$(build.artifactstagingdirectory)' #'$(Build.SourcesDirectory)'
    - task: CmdLine@2
      inputs:
          script: |
            echo Hello world-2
            echo  $(Build.SourcesDirectory)
            echo Hello world-2
    # Step 2: Copy Web API files to IIS server folder
    - task: CopyFiles@2
      displayName: 'Copy Web API files to IIS folder'
      inputs:
        SourceFolder: '$(build.artifactstagingdirectory)' #'$(buildOutputFolder)/webapi'
        Contents: '**'
        TargetFolder: 'C:\inetpub\wwwroot\myfolder'  # Change this path to your IIS folder   
    - task: CmdLine@2
      inputs:
          script: |
            echo Artifact staging directory-Hello world-3
            echo  $(Build.ArtifactStagingDirectory)
            echo Hello world-3

            echo Sources Directory- Hello world-3
            echo  $(Build.SourcesDirectory)
            echo Hello world-3
